"""Phase-C durable refresh schema contracts."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

MIGRATION = (
    ROOT
    / "alembic"
    / "versions"
    / "f31a9c7d2e04_durable_refresh_coordination.py"
)

UP = MIGRATION.with_name(
    "f31a9c7d2e04_durable_refresh_coordination_up.sql"
)

SERVICE = (
    ROOT
    / "auction_etl"
    / "services"
    / "refresh_jobs.py"
)


def test_phase_c_migration_follows_current_alembic_head() -> None:
    """Durable coordination extends the validated Phase-B schema head."""
    source = MIGRATION.read_text(
        encoding="utf-8"
    )

    assert 'revision: str = "f31a9c7d2e04"' in source
    assert 'down_revision: str | None = "c8b4d7e2a619"' in source


def test_phase_c_creates_durable_operational_tables() -> None:
    """The migration installs the three documented coordination tables."""
    source = UP.read_text(
        encoding="utf-8"
    )

    for relation in (
        "ops.refresh_job",
        "ops.refresh_marketplace",
        "ops.refresh_event",
    ):
        assert (
            f"CREATE TABLE {relation}"
            in source
        )

    for value in (
        "lease_owner",
        "lease_expires_at",
        "heartbeat_at",
        "cancel_requested_at",
        "consecutive_known_at_stop",
        "GENERATED BY DEFAULT AS IDENTITY",
        "jsonb",
    ):
        assert value in source


def test_phase_c_enforces_one_active_refresh() -> None:
    """Database constraints preserve the single authoritative writer boundary."""
    source = UP.read_text(
        encoding="utf-8"
    )

    assert "refresh_job_single_active_idx" in source
    assert "WHERE state IN ('queued', 'running')" in source


def test_phase_c_service_uses_transactional_claiming() -> None:
    """Workers claim durable work with PostgreSQL row locking."""
    source = SERVICE.read_text(
        encoding="utf-8"
    )

    assert "FOR UPDATE SKIP LOCKED" in source
    assert "pg_advisory_xact_lock" in source
    assert "claim_next_refresh_job" in source
    assert "heartbeat_refresh_job" in source
    assert "requeue_expired_refresh_jobs" in source
    assert "RefreshLeaseLost" in source
