"""initial warehouse schema

Revision ID: 4c4e55331d0d
Revises: 
Create Date: 2026-07-21 12:16:29.487066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4e55331d0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    schema='raw'
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='system'
    )
    op.create_table('auction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.String(length=32), nullable=False),
    sa.Column('listing_id', sa.String(length=128), nullable=False),
    sa.Column('auction_url', sa.Text(), nullable=False),
    sa.Column('seller', sa.String(length=128), nullable=True),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=64), nullable=True),
    sa.Column('edition', sa.String(length=64), nullable=True),
    sa.Column('catalog_number', sa.String(length=128), nullable=True),
    sa.Column('condition_media', sa.String(length=64), nullable=True),
    sa.Column('condition_cover', sa.String(length=64), nullable=True),
    sa.Column('bulk_lot', sa.Boolean(), nullable=False),
    sa.Column('bid_count', sa.Integer(), nullable=True),
    sa.Column('watch_count', sa.Integer(), nullable=True),
    sa.Column('start_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipping_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='warehouse'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auction', schema='warehouse')
    op.drop_table('source', schema='system')
    op.drop_table('page', schema='raw')
    # ### end Alembic commands ###
