"""add crawl job

Revision ID: c4aba410158b
Revises: 4c4e55331d0d
Create Date: 2026-07-21 12:21:36.279168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4aba410158b'
down_revision: Union[str, Sequence[str], None] = '4c4e55331d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='system'
    )
    op.add_column('page', sa.Column('crawl_job_id', sa.Integer(), nullable=True), schema='raw')
    op.create_foreign_key(None, 'page', 'crawl_job', ['crawl_job_id'], ['id'], source_schema='raw', referent_schema='system')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'page', schema='raw', type_='foreignkey')
    op.drop_column('page', 'crawl_job_id', schema='raw')
    op.drop_table('crawl_job', schema='system')
    # ### end Alembic commands ###
