CREATE OR REPLACE VIEW analytics.emotional_damage AS
WITH first_press AS (
         SELECT auction_collector_base.release_family_id,
            auction_collector_base.media_type,
            percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY (auction_collector_base.fully_normalized_price_usd::double precision)) AS first_press_median
           FROM analytics.auction_collector_base
          WHERE auction_collector_base.is_first_press AND auction_collector_base.fully_normalized_price_usd IS NOT NULL
          GROUP BY auction_collector_base.release_family_id, auction_collector_base.media_type
        ), complete_price AS (
         SELECT auction_collector_base.pressing_id,
            percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY (auction_collector_base.condition_adjusted_price_usd::double precision)) AS complete_median
           FROM analytics.auction_collector_base
          WHERE auction_collector_base.completeness_status = 'COMPLETE'::text AND auction_collector_base.condition_adjusted_price_usd IS NOT NULL
          GROUP BY auction_collector_base.pressing_id
        ), components AS (
         SELECT score.id,
            score.marketplace,
            score.listing_id,
            score.auction_url,
            score.seller,
            score.artist,
            score.title,
            score.media_type,
            score.edition,
            score.catalog_number,
            score.condition_media,
            score.condition_cover,
            score.bulk_lot,
            score.bid_count,
            score.watch_count,
            score.start_price,
            score.final_price,
            score.shipping_price,
            score.tax_amount,
            score.currency,
            score.ended_at,
            score.created_at,
            score.gross_price,
            score.tax_rate,
            score.price_includes_tax,
            score.disc_count,
            score.opening_at,
            score.closing_at,
            score.current_price_gross,
            score.buyout_price_gross,
            score.detail_status,
            score.detail_fetched_at,
            score.fx_rate_to_usd,
            score.fx_rate_date,
            score.start_price_usd,
            score.final_price_usd,
            score.shipping_price_usd,
            score.tax_usd,
            score.gross_price_usd,
            score.landed_price_usd,
            score.current_price_usd,
            score.buyout_price_usd,
            score.auction_format,
            score.pressing_id,
            score.release_family_id,
            score.canonical_artist,
            score.canonical_release_title,
            score.canonical_catalog_number,
            score.canonical_matrix_number,
            score.pressing_region,
            score.pressing_country,
            score.pressing_generation,
            score.pressing_variant_key,
            score.pressing_variant_label,
            score.is_first_press,
            score.is_modern_repress,
            score.canonical_disc_count,
            score.pressing_match_basis,
            score.pressing_match_confidence,
            score.required_component_count,
            score.present_required_component_count,
            score.missing_components,
            score.unverified_components,
            score.unexpected_components,
            score.completeness_ratio,
            score.completeness_status,
            score.complete,
            score.obi_state,
            score.obi_variant_key,
            score.sealed_state,
            score.media_grade_code,
            score.cover_grade_code,
            score.media_condition_rank,
            score.cover_condition_rank,
            score.media_condition_score,
            score.cover_condition_score,
            score.distinct_bidder_count,
            score.distinct_bidder_state,
            score.distinct_bidder_source,
            score.closing_window_minutes,
            score.closing_window_start_price,
            score.closing_window_final_price,
            score.closing_window_currency,
            score.closing_window_escalation_ratio,
            score.seller_group,
            score.seller_kind,
            score.event_type,
            score.private_collection,
            score.record_shop_inventory,
            score.rolling_auction,
            score.relisted,
            score.interrupted,
            score.withdrawn,
            score.lineage_id,
            score.price_basis,
            score.title_strength_score,
            score.market_context_score,
            score.manual_auction_behavior_score,
            score.expectation_price_usd,
            score.historical_anchor_usd,
            score.condition_market_factor,
            score.completeness_market_factor,
            score.price_hammer_local,
            score.price_gross_local,
            score.price_landed_local,
            score.price_hammer_usd,
            score.price_gross_usd,
            score.price_landed_usd,
            score.selected_price_local,
            score.selected_price_usd,
            score.condition_adjusted_price_usd,
            score.fully_normalized_price_usd,
            score.normalization_ready,
            score.bid_component,
            score.watcher_component,
            score.bidder_component,
            score.escalation_component,
            score.behavior_points,
            score.behavior_available_points,
            score.completeness_score,
            score.condition_score,
            score.auction_behavior_score,
            score.auction_behavior_coverage,
            score.plushie_index,
            score.plushie_partial_score,
            score.plushie_coverage,
                CASE
                    WHEN score.expectation_price_usd > 0::numeric AND score.selected_price_usd IS NOT NULL THEN LEAST(20::numeric, abs(score.selected_price_usd / score.expectation_price_usd - 1::numeric) * 20::numeric)
                    ELSE NULL::numeric
                END AS expectation_deviation,
                CASE
                    WHEN score.closing_window_escalation_ratio IS NOT NULL THEN LEAST(20::numeric, GREATEST(score.closing_window_escalation_ratio, 0::numeric) * 10::numeric)
                    ELSE NULL::numeric
                END AS late_spike,
                CASE
                    WHEN score.historical_anchor_usd > 0::numeric AND score.selected_price_usd IS NOT NULL THEN LEAST(20::numeric, abs(score.selected_price_usd / score.historical_anchor_usd - 1::numeric) * 10::numeric)
                    ELSE NULL::numeric
                END AS historical_anchor_deviation,
                CASE
                    WHEN score.completeness_status = 'INCOMPLETE'::text AND complete_price.complete_median > 0::double precision AND score.condition_adjusted_price_usd::double precision > complete_price.complete_median THEN LEAST(20::double precision, (score.condition_adjusted_price_usd::double precision / complete_price.complete_median - 1::double precision) * 20::double precision)
                    ELSE NULL::double precision
                END AS completeness_contradiction,
                CASE
                    WHEN score.is_modern_repress AND first_press.first_press_median > 0::double precision AND score.fully_normalized_price_usd::double precision > first_press.first_press_median THEN LEAST(20::double precision, (score.fully_normalized_price_usd::double precision / first_press.first_press_median - 1::double precision) * 20::double precision)
                    ELSE NULL::double precision
                END AS first_press_distortion,
            score.auction_behavior_score AS bidder_war_intensity
           FROM analytics.auction_scores score
             LEFT JOIN first_press ON first_press.release_family_id = score.release_family_id AND first_press.media_type::text = score.media_type::text
             LEFT JOIN complete_price ON complete_price.pressing_id = score.pressing_id
        ), summed AS (
         SELECT components.id,
            components.marketplace,
            components.listing_id,
            components.auction_url,
            components.seller,
            components.artist,
            components.title,
            components.media_type,
            components.edition,
            components.catalog_number,
            components.condition_media,
            components.condition_cover,
            components.bulk_lot,
            components.bid_count,
            components.watch_count,
            components.start_price,
            components.final_price,
            components.shipping_price,
            components.tax_amount,
            components.currency,
            components.ended_at,
            components.created_at,
            components.gross_price,
            components.tax_rate,
            components.price_includes_tax,
            components.disc_count,
            components.opening_at,
            components.closing_at,
            components.current_price_gross,
            components.buyout_price_gross,
            components.detail_status,
            components.detail_fetched_at,
            components.fx_rate_to_usd,
            components.fx_rate_date,
            components.start_price_usd,
            components.final_price_usd,
            components.shipping_price_usd,
            components.tax_usd,
            components.gross_price_usd,
            components.landed_price_usd,
            components.current_price_usd,
            components.buyout_price_usd,
            components.auction_format,
            components.pressing_id,
            components.release_family_id,
            components.canonical_artist,
            components.canonical_release_title,
            components.canonical_catalog_number,
            components.canonical_matrix_number,
            components.pressing_region,
            components.pressing_country,
            components.pressing_generation,
            components.pressing_variant_key,
            components.pressing_variant_label,
            components.is_first_press,
            components.is_modern_repress,
            components.canonical_disc_count,
            components.pressing_match_basis,
            components.pressing_match_confidence,
            components.required_component_count,
            components.present_required_component_count,
            components.missing_components,
            components.unverified_components,
            components.unexpected_components,
            components.completeness_ratio,
            components.completeness_status,
            components.complete,
            components.obi_state,
            components.obi_variant_key,
            components.sealed_state,
            components.media_grade_code,
            components.cover_grade_code,
            components.media_condition_rank,
            components.cover_condition_rank,
            components.media_condition_score,
            components.cover_condition_score,
            components.distinct_bidder_count,
            components.distinct_bidder_state,
            components.distinct_bidder_source,
            components.closing_window_minutes,
            components.closing_window_start_price,
            components.closing_window_final_price,
            components.closing_window_currency,
            components.closing_window_escalation_ratio,
            components.seller_group,
            components.seller_kind,
            components.event_type,
            components.private_collection,
            components.record_shop_inventory,
            components.rolling_auction,
            components.relisted,
            components.interrupted,
            components.withdrawn,
            components.lineage_id,
            components.price_basis,
            components.title_strength_score,
            components.market_context_score,
            components.manual_auction_behavior_score,
            components.expectation_price_usd,
            components.historical_anchor_usd,
            components.condition_market_factor,
            components.completeness_market_factor,
            components.price_hammer_local,
            components.price_gross_local,
            components.price_landed_local,
            components.price_hammer_usd,
            components.price_gross_usd,
            components.price_landed_usd,
            components.selected_price_local,
            components.selected_price_usd,
            components.condition_adjusted_price_usd,
            components.fully_normalized_price_usd,
            components.normalization_ready,
            components.bid_component,
            components.watcher_component,
            components.bidder_component,
            components.escalation_component,
            components.behavior_points,
            components.behavior_available_points,
            components.completeness_score,
            components.condition_score,
            components.auction_behavior_score,
            components.auction_behavior_coverage,
            components.plushie_index,
            components.plushie_partial_score,
            components.plushie_coverage,
            components.expectation_deviation,
            components.late_spike,
            components.historical_anchor_deviation,
            components.completeness_contradiction,
            components.first_press_distortion,
            components.bidder_war_intensity,
            (COALESCE(components.expectation_deviation, 0::numeric) + COALESCE(components.late_spike, 0::numeric) + COALESCE(components.historical_anchor_deviation, 0::numeric))::double precision + COALESCE(components.completeness_contradiction, 0::double precision) + COALESCE(components.first_press_distortion, 0::double precision) + COALESCE(components.bidder_war_intensity, 0::numeric)::double precision AS damage_points,
                CASE
                    WHEN components.expectation_deviation IS NOT NULL THEN 1
                    ELSE 0
                END +
                CASE
                    WHEN components.late_spike IS NOT NULL THEN 1
                    ELSE 0
                END +
                CASE
                    WHEN components.historical_anchor_deviation IS NOT NULL THEN 1
                    ELSE 0
                END +
                CASE
                    WHEN components.completeness_contradiction IS NOT NULL THEN 1
                    ELSE 0
                END +
                CASE
                    WHEN components.first_press_distortion IS NOT NULL THEN 1
                    ELSE 0
                END +
                CASE
                    WHEN components.bidder_war_intensity IS NOT NULL THEN 1
                    ELSE 0
                END AS damage_components
           FROM components
        ), scored AS (
         SELECT summed.id,
            summed.marketplace,
            summed.listing_id,
            summed.auction_url,
            summed.seller,
            summed.artist,
            summed.title,
            summed.media_type,
            summed.edition,
            summed.catalog_number,
            summed.condition_media,
            summed.condition_cover,
            summed.bulk_lot,
            summed.bid_count,
            summed.watch_count,
            summed.start_price,
            summed.final_price,
            summed.shipping_price,
            summed.tax_amount,
            summed.currency,
            summed.ended_at,
            summed.created_at,
            summed.gross_price,
            summed.tax_rate,
            summed.price_includes_tax,
            summed.disc_count,
            summed.opening_at,
            summed.closing_at,
            summed.current_price_gross,
            summed.buyout_price_gross,
            summed.detail_status,
            summed.detail_fetched_at,
            summed.fx_rate_to_usd,
            summed.fx_rate_date,
            summed.start_price_usd,
            summed.final_price_usd,
            summed.shipping_price_usd,
            summed.tax_usd,
            summed.gross_price_usd,
            summed.landed_price_usd,
            summed.current_price_usd,
            summed.buyout_price_usd,
            summed.auction_format,
            summed.pressing_id,
            summed.release_family_id,
            summed.canonical_artist,
            summed.canonical_release_title,
            summed.canonical_catalog_number,
            summed.canonical_matrix_number,
            summed.pressing_region,
            summed.pressing_country,
            summed.pressing_generation,
            summed.pressing_variant_key,
            summed.pressing_variant_label,
            summed.is_first_press,
            summed.is_modern_repress,
            summed.canonical_disc_count,
            summed.pressing_match_basis,
            summed.pressing_match_confidence,
            summed.required_component_count,
            summed.present_required_component_count,
            summed.missing_components,
            summed.unverified_components,
            summed.unexpected_components,
            summed.completeness_ratio,
            summed.completeness_status,
            summed.complete,
            summed.obi_state,
            summed.obi_variant_key,
            summed.sealed_state,
            summed.media_grade_code,
            summed.cover_grade_code,
            summed.media_condition_rank,
            summed.cover_condition_rank,
            summed.media_condition_score,
            summed.cover_condition_score,
            summed.distinct_bidder_count,
            summed.distinct_bidder_state,
            summed.distinct_bidder_source,
            summed.closing_window_minutes,
            summed.closing_window_start_price,
            summed.closing_window_final_price,
            summed.closing_window_currency,
            summed.closing_window_escalation_ratio,
            summed.seller_group,
            summed.seller_kind,
            summed.event_type,
            summed.private_collection,
            summed.record_shop_inventory,
            summed.rolling_auction,
            summed.relisted,
            summed.interrupted,
            summed.withdrawn,
            summed.lineage_id,
            summed.price_basis,
            summed.title_strength_score,
            summed.market_context_score,
            summed.manual_auction_behavior_score,
            summed.expectation_price_usd,
            summed.historical_anchor_usd,
            summed.condition_market_factor,
            summed.completeness_market_factor,
            summed.price_hammer_local,
            summed.price_gross_local,
            summed.price_landed_local,
            summed.price_hammer_usd,
            summed.price_gross_usd,
            summed.price_landed_usd,
            summed.selected_price_local,
            summed.selected_price_usd,
            summed.condition_adjusted_price_usd,
            summed.fully_normalized_price_usd,
            summed.normalization_ready,
            summed.bid_component,
            summed.watcher_component,
            summed.bidder_component,
            summed.escalation_component,
            summed.behavior_points,
            summed.behavior_available_points,
            summed.completeness_score,
            summed.condition_score,
            summed.auction_behavior_score,
            summed.auction_behavior_coverage,
            summed.plushie_index,
            summed.plushie_partial_score,
            summed.plushie_coverage,
            summed.expectation_deviation,
            summed.late_spike,
            summed.historical_anchor_deviation,
            summed.completeness_contradiction,
            summed.first_press_distortion,
            summed.bidder_war_intensity,
            summed.damage_points,
            summed.damage_components,
                CASE
                    WHEN summed.damage_components = 0 THEN NULL::numeric
                    ELSE round((summed.damage_points / (summed.damage_components * 20)::double precision * 100::double precision)::numeric, 2)
                END AS emotional_damage_score,
            round(summed.damage_components::numeric / 6::numeric, 4) AS emotional_damage_coverage
           FROM summed
        )
 SELECT id,
    marketplace,
    listing_id,
    auction_url,
    seller,
    artist,
    title,
    media_type,
    edition,
    catalog_number,
    condition_media,
    condition_cover,
    bulk_lot,
    bid_count,
    watch_count,
    start_price,
    final_price,
    shipping_price,
    tax_amount,
    currency,
    ended_at,
    created_at,
    gross_price,
    tax_rate,
    price_includes_tax,
    disc_count,
    opening_at,
    closing_at,
    current_price_gross,
    buyout_price_gross,
    detail_status,
    detail_fetched_at,
    fx_rate_to_usd,
    fx_rate_date,
    start_price_usd,
    final_price_usd,
    shipping_price_usd,
    tax_usd,
    gross_price_usd,
    landed_price_usd,
    current_price_usd,
    buyout_price_usd,
    auction_format,
    pressing_id,
    release_family_id,
    canonical_artist,
    canonical_release_title,
    canonical_catalog_number,
    canonical_matrix_number,
    pressing_region,
    pressing_country,
    pressing_generation,
    pressing_variant_key,
    pressing_variant_label,
    is_first_press,
    is_modern_repress,
    canonical_disc_count,
    pressing_match_basis,
    pressing_match_confidence,
    required_component_count,
    present_required_component_count,
    missing_components,
    unverified_components,
    unexpected_components,
    completeness_ratio,
    completeness_status,
    complete,
    obi_state,
    obi_variant_key,
    sealed_state,
    media_grade_code,
    cover_grade_code,
    media_condition_rank,
    cover_condition_rank,
    media_condition_score,
    cover_condition_score,
    distinct_bidder_count,
    distinct_bidder_state,
    distinct_bidder_source,
    closing_window_minutes,
    closing_window_start_price,
    closing_window_final_price,
    closing_window_currency,
    closing_window_escalation_ratio,
    seller_group,
    seller_kind,
    event_type,
    private_collection,
    record_shop_inventory,
    rolling_auction,
    relisted,
    interrupted,
    withdrawn,
    lineage_id,
    price_basis,
    title_strength_score,
    market_context_score,
    manual_auction_behavior_score,
    expectation_price_usd,
    historical_anchor_usd,
    condition_market_factor,
    completeness_market_factor,
    price_hammer_local,
    price_gross_local,
    price_landed_local,
    price_hammer_usd,
    price_gross_usd,
    price_landed_usd,
    selected_price_local,
    selected_price_usd,
    condition_adjusted_price_usd,
    fully_normalized_price_usd,
    normalization_ready,
    bid_component,
    watcher_component,
    bidder_component,
    escalation_component,
    behavior_points,
    behavior_available_points,
    completeness_score,
    condition_score,
    auction_behavior_score,
    auction_behavior_coverage,
    plushie_index,
    plushie_partial_score,
    plushie_coverage,
    expectation_deviation,
    late_spike,
    historical_anchor_deviation,
    completeness_contradiction,
    first_press_distortion,
    bidder_war_intensity,
    damage_points,
    damage_components,
    emotional_damage_score,
    emotional_damage_coverage,
        CASE
            WHEN emotional_damage_score IS NULL
             OR emotional_damage_coverage < 0.5::numeric
        THEN 'INSUFFICIENT_DATA'::text
            WHEN emotional_damage_score >= 90::numeric THEN 'SKINWALKER_RANCH'::text
            WHEN emotional_damage_score >= 75::numeric THEN 'SEV_0'::text
            WHEN emotional_damage_score >= 60::numeric THEN 'BIDDER_IDENTITY_WAR'::text
            WHEN emotional_damage_score >= 40::numeric THEN 'MAJOR_INCIDENT'::text
            WHEN emotional_damage_score >= 20::numeric THEN 'ELEVATED'::text
            ELSE 'NORMAL'::text
        END AS incident_class
   FROM scored;
