CREATE SCHEMA IF NOT EXISTS ops;

CREATE TABLE ops.refresh_job (
    id uuid PRIMARY KEY,
    state text NOT NULL DEFAULT 'queued',
    requested_at timestamptz NOT NULL DEFAULT now(),
    requested_by text,
    trigger text NOT NULL DEFAULT 'api',
    started_at timestamptz,
    finished_at timestamptz,
    source_commit text,
    lease_owner text,
    lease_expires_at timestamptz,
    heartbeat_at timestamptz,
    attempt integer NOT NULL DEFAULT 0,
    cancel_requested_at timestamptz,
    message text,
    error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT refresh_job_state_check
        CHECK (
            state IN (
                'queued',
                'running',
                'completed',
                'failed',
                'cancelled'
            )
        ),
    CONSTRAINT refresh_job_attempt_check
        CHECK (
            attempt >= 0
        ),
    CONSTRAINT refresh_job_running_lease_check
        CHECK (
            state <> 'running'
            OR (
                lease_owner IS NOT NULL
                AND lease_expires_at IS NOT NULL
                AND heartbeat_at IS NOT NULL
            )
        )
);

CREATE UNIQUE INDEX refresh_job_single_active_idx
    ON ops.refresh_job ((1))
    WHERE state IN ('queued', 'running');

CREATE INDEX refresh_job_queue_idx
    ON ops.refresh_job (
        requested_at,
        created_at,
        id
    )
    WHERE state = 'queued';

CREATE INDEX refresh_job_lease_idx
    ON ops.refresh_job (
        lease_expires_at
    )
    WHERE state = 'running';

CREATE TABLE ops.refresh_marketplace (
    job_id uuid NOT NULL
        REFERENCES ops.refresh_job(id)
        ON DELETE CASCADE,
    marketplace text NOT NULL,
    ordinal integer NOT NULL,
    state text NOT NULL DEFAULT 'waiting',
    started_at timestamptz,
    finished_at timestamptz,
    discovered integer NOT NULL DEFAULT 0,
    already_known integer NOT NULL DEFAULT 0,
    new_count integer NOT NULL DEFAULT 0,
    detail_scraped integer NOT NULL DEFAULT 0,
    detail_skipped integer NOT NULL DEFAULT 0,
    discovery_pages integer NOT NULL DEFAULT 0,
    consecutive_known_at_stop integer NOT NULL DEFAULT 0,
    message text,
    error text,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (
        job_id,
        marketplace
    ),
    CONSTRAINT refresh_marketplace_ordinal_unique
        UNIQUE (
            job_id,
            ordinal
        ),
    CONSTRAINT refresh_marketplace_name_check
        CHECK (
            marketplace IN (
                'buyee',
                'ebay',
                'gripsweat'
            )
        ),
    CONSTRAINT refresh_marketplace_state_check
        CHECK (
            state IN (
                'waiting',
                'running',
                'done',
                'failed',
                'skipped'
            )
        ),
    CONSTRAINT refresh_marketplace_ordinal_check
        CHECK (
            ordinal BETWEEN 1 AND 3
        ),
    CONSTRAINT refresh_marketplace_counters_check
        CHECK (
            discovered >= 0
            AND already_known >= 0
            AND new_count >= 0
            AND detail_scraped >= 0
            AND detail_skipped >= 0
            AND discovery_pages >= 0
            AND consecutive_known_at_stop >= 0
        )
);

CREATE INDEX refresh_marketplace_state_idx
    ON ops.refresh_marketplace (
        state,
        job_id,
        ordinal
    );

CREATE TABLE ops.refresh_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id uuid NOT NULL
        REFERENCES ops.refresh_job(id)
        ON DELETE CASCADE,
    marketplace text,
    event_type text NOT NULL,
    message text,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT refresh_event_marketplace_check
        CHECK (
            marketplace IS NULL
            OR marketplace IN (
                'buyee',
                'ebay',
                'gripsweat'
            )
        )
);

CREATE INDEX refresh_event_job_idx
    ON ops.refresh_event (
        job_id,
        id
    );
